name = "PyCallJLD2"
uuid = "07b0ad8c-101f-43fe-82b6-eff101a491e1"
authors = ["Sasha Petrenko <sap625@mst.edu>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
DocStringExtensions = "0.9"
JLD2 = "0.4"
PyCall = "1"
Pkg = "1.9"
