name = "PyCallJLD2"
uuid = "07b0ad8c-101f-43fe-82b6-eff101a491e1"
authors = ["Sasha Petrenko <sap625@mst.edu>"]
version = "0.1.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
JLD2 = "0.4"
PyCall = "1"
