name = "PyCallJLD2"
uuid = "07b0ad8c-101f-43fe-82b6-eff101a491e1"
authors = ["Sasha Petrenko <sap625@mst.edu>"]
description = "A Julia package for saving and loading PyCall.PyObjects with JLD2."
version = "0.1.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
DocStringExtensions = "0.9"
JLD2 = "0.4"
Pkg = "<0.0.1, 1"
PyCall = "1"
julia = "1"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "Logging"]
